### ISSUE TITLE
Complete code being displayed on single line

### ISSUE THREAD

**Issue by mdtareque** [algorithm-visualizer/algorithm-visualizer#20]
The entire code (in DP category at least) is being cramblef and displayed on a single line, making it hard to read. FYI, I am using mobile chrome browser. Rest all animation working good. Please take a look at this issue.

**Comment by parkjs814** [comment]
Can you upload a screenshot of it using http://imgur.com ?

**Comment by mdtareque** [comment]
http://i.imgur.com/3Kc5inF.jpg
The code on right side in all in one line. Is this intended?

**Comment by parkjs814** [comment]
Ugh, that is weird. Is it JellyBean?

**Comment by nem035** [comment]
@mdtareque is this still happening or can the issue be closed?
