### ISSUE TITLE
Migration to React.js

### ISSUE THREAD

**Issue by parkjs814** [algorithm-visualizer/algorithm-visualizer#229]
I was looking into the code to add several more features, but I found it quite messy overall. Especially, CSS and Tracer parts were horrible as they were written not long after I began web programming. The readability got much better after @nem035 thankfully rewrote everything in ES6 (#48) about 2 years ago. (Already!) I believe migrating to React.js will do even more. I will be working on rewriting everything in the combination of React.js + SASS + Webpack to make the code more comprehensible and modularized. Several changes to UX/UI and Tracer will be followed.

**Comment by nem035** [comment]
I'm down to help with anything if needed 🙂

I also suggest to go the [CSS-in-JS](https://hackernoon.com/all-you-need-to-know-about-css-in-js-984a72d48ebc) way with [styled-components](styled-components.com) or maybe [glamorous](https://github.com/paypal/glamorous) rather than SASS

**Comment by parkjs814** [comment]
@nem035 Cool :+1: I will go the CSS-in-JS way with Webpack's [css-loader](https://github.com/webpack-contrib/css-loader). I am also planning to use SASS along with it.

**Comment by TornjV** [comment]
Down for it also!

👍 For styled-components

**Comment by ChakshuGautam** [comment]
Would like to help too. Is there a branch you guys are working on?
