### ISSUE TITLE
Visualization Not Found

### ISSUE THREAD

**Issue by suiyueranzly** [algorithm-visualizer/algorithm-visualizer#235]
it has a error when i build my Java code. like this : 

![s1exqdtej1](https://user-images.githubusercontent.com/27992898/52754930-2db9da00-3037-11e9-844b-71caebb64050.png)

**Comment by parkjs814** [comment]
Sorry, it is due to the updates I made to tracers a few hours ago. I am working on it and expecting to fix it soon.
