### ISSUE TITLE
the java code doesn't seem to work

### ISSUE THREAD

**Issue by suiyueranzly** [algorithm-visualizer/algorithm-visualizer#236]
when i build the java code . it has a error , like this :

![bmvmsqba8n](https://user-images.githubusercontent.com/27992898/52827333-59a09280-30ff-11e9-8c5a-0ae52f58404d.png)

**Comment by parkjs814** [comment]
I have not documented yet, but I recently added/removed some features including:
- disabling method chaining.
```java
chartTracer.select(j);
chartTracer.select(j + 1);
```
- adding layout classes.
```java
Layout.setRoot(new VerticalLayout(new Commander[]{chartTracer, logTracer}));
```
- making `.delay()` static.
```java
Tracer.delay()
```

I just updated the [visualization of Bubble Sort](https://algorithm-visualizer.org/brute-force/bubble-sort) accordingly.
