### ISSUE TITLE
*.java file doesn't seem to work

### ISSUE THREAD

**Issue by suiyueranzly** [algorithm-visualizer/algorithm-visualizer#238]
when i build the java code . it has a error , like this :

![image](https://user-images.githubusercontent.com/27992898/54261201-19b9b780-45a6-11e9-81f9-777829111e95.png)

**Comment by parkjs814** [comment]
Oops, I just fixed it by increasing the volume size. It was due to large Docker images taking most of the space. Thanks for letting me know!
