### ISSUE TITLE
Stop at this window

### ISSUE THREAD

**Issue by huanglianghui** [algorithm-visualizer/algorithm-visualizer#252]
Compile successfully, but can't see the effect

**Comment by parkjs814** [comment]
Which window?

**Comment by huanglianghui** [comment]
![捕获](https://user-images.githubusercontent.com/51328155/59142554-b1d30b80-89f2-11e9-9b23-5ea0a776270c.PNG)

**Comment by parkjs814** [comment]
Have you tried opening `http://localhost:8080/` in your browser?

**Comment by huanglianghui** [comment]
It turned out to be like this, thank you.

**Comment by parkjs814** [comment]
Turned out to be like what?

**Comment by huanglianghui** [comment]
Already run successfully
