### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by Git4Mark** [algorithm-visualizer/algorithm-visualizer#254]
environment: os windows10, npm@6.9.0 node@v10.15.0

error stack:

> @algorithm-visualizer/algorithm-visualizer@2.0.0 dev F:\git\algorithm-visualizer
> NODE_ENV=development ./bin/www

'NODE_ENV' not an internal or external command, nor a runnable program Or batch files
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @algorithm-visualizer/algorithm-visualizer@2.0.0 dev: `NODE_ENV=development ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @algorithm-visualizer/algorithm-visualizer@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\soft\npm\npm-cache\_logs\2019-06-09T16_45_57_481Z-debug.log

F:\git\algorithm-visualizer>npm run dev > error.log
'NODE_ENV' not an internal or external command, nor a runnable program Or batch files
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @algorithm-visualizer/algorithm-visualizer@2.0.0 dev: `NODE_ENV=development ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @algorithm-visualizer/algorithm-visualizer@2.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\soft\npm\npm-cache\_logs\2019-06-09T16_47_19_414Z-debug.log

D:\soft\npm\npm-cache\_logs\2019-06-09T16_47_19_414Z-debug.log：
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\soft\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.9.0
3 info using node@v10.15.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~predev: @algorithm-visualizer/algorithm-visualizer@2.0.0
6 info lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~dev: @algorithm-visualizer/algorithm-visualizer@2.0.0
7 verbose lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~dev: PATH: D:\soft\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\git\algorithm-visualizer\node_modules\.bin;F:\git\algorithm-visualizer\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;D:\soft\Java\jdk_release\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\soft\Git\cmd;D:\soft\pycSafefile\x64;D:\soft\apache-maven\release\bin;D:\soft\Anaconda3\Scripts;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Go\bin;C:\Program Files\NVIDIA Corporation\NVSMI;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\soft\gradle\latest\bin;D:\soft\npm;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;D:\soft\k8s\kubectl.exe;C:\Users\MARK\AppData\Local\Microsoft\WindowsApps;D:\soft\Microsoft VS Code\bin;C:\Users\MARK\AppData\Roaming\npm;C:\Users\MARK\go\bin;C:\Go\bin;;C:\Program Files\JetBrains\GoLand 2018.3.5\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1\bin;C:\Program Files\JetBrains\PyCharm 2018.3.5\bin;C:\Program Files\JetBrains\WebStorm 2018.3.5\bin;D:\soft\Fiddler;C:\Users\MARK\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\CLion 2019.1.4\bin;
9 verbose lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~dev: CWD: F:\git\algorithm-visualizer
10 silly lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~dev: Args: [ '/d /s /c', 'NODE_ENV=development ./bin/www' ]
11 silly lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~dev: Failed to exec dev script
13 verbose stack Error: @algorithm-visualizer/algorithm-visualizer@2.0.0 dev: `NODE_ENV=development ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\soft\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\soft\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @algorithm-visualizer/algorithm-visualizer@2.0.0
15 verbose cwd F:\git\algorithm-visualizer
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "D:\\soft\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v10.15.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @algorithm-visualizer/algorithm-visualizer@2.0.0 dev: `NODE_ENV=development ./bin/www`
22 error Exit status 1
23 error Failed at the @algorithm-visualizer/algorithm-visualizer@2.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by parkjs814** [comment]
Hi, I updated the documentation just now. Can you follow [these instructions](https://github.com/algorithm-visualizer/algorithm-visualizer/blob/master/CONTRIBUTING.md#running-locally) to see if it works?

**Comment by Git4Mark** [comment]
@parkjs814
following the latest instructions,   **'npm start**' failed
**error stack :**
```

> @algorithm-visualizer/algorithm-visualizer@2.0.0 start H:\git\algorithm-visualizer
> react-scripts start

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './util'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (H:\git\algorithm-visualizer\node_modules\bluebird\js\release\promise.js:14:12)
    at Object.<anonymous> (H:\git\algorithm-visualizer\node_modules\bluebird\js\release\bluebird.js:9:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @algorithm-visualizer/algorithm-visualizer@2.0.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @algorithm-visualizer/algorithm-visualizer@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\node_soft\node_cache\_logs\2019-06-10T07_23_18_151Z-debug.log

```
**2019-06-10T07_23_18_151Z-debug.log:**
```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\node_soft\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~prestart: @algorithm-visualizer/algorithm-visualizer@2.0.0
6 info lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~start: @algorithm-visualizer/algorithm-visualizer@2.0.0
7 verbose lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~start: PATH: D:\node_soft\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\git\algorithm-visualizer\node_modules\.bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Boxstarter;D:\app\wangrui\product\11.2.0\dbhome_2\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Java\jdk1.8.0_151\bin;D:\Java\jdk1.8.0_151\jre\bin;D:\apache-maven\release\bin;E:\JDBC\mysql\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft VS Code\bin;C:\Go\bin;C:\Program Files (x86)\pycSafefile\x64;C:\ProgramData\chocolatey\bin;D:\win-shell;C:\Program Files (x86)\Tesseract-OCR;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\dotnet\;C:\Users\wangrui\AppData\Local\Microsoft\WindowsApps;D:\Java\jdk1.8.0_151\bin;D:\Java\jdk1.8.0_151\jre\bin;C:\Program Files\Bandizip\;C:\Users\wangrui\AppData\Local\Microsoft\WindowsApps;D:\Program Files\erl9.3\bin;E:\soft\service-register\;D:\Anaconda3\Scripts;D:\groovy-2.5.1\bin;E:\gradle-4.9\bin;C:\Users\wangrui\go\bin;D:\soft\rabbitmq_server-3.7.5\sbin;C:\Users\wangrui\AppData\Roaming\npm;C:\Users\wangrui\AppData\Local\Yarn\bin;C:\Program Files\JetBrains\GoLand 2019.1.2\bin;;C:\Program Files\JetBrains\PyCharm 2018.3.5\bin;;C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.6\bin;;D:\node_soft;D:\soft\k8s\kubectl.exe;D:\soft\wkhtmltox\bin\wkhtmltopdf.exe;
9 verbose lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~start: CWD: H:\git\algorithm-visualizer
10 silly lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle @algorithm-visualizer/algorithm-visualizer@2.0.0~start: Failed to exec start script
13 verbose stack Error: @algorithm-visualizer/algorithm-visualizer@2.0.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\node_soft\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\node_soft\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid @algorithm-visualizer/algorithm-visualizer@2.0.0
15 verbose cwd H:\git\algorithm-visualizer
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "D:\\node_soft\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @algorithm-visualizer/algorithm-visualizer@2.0.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the @algorithm-visualizer/algorithm-visualizer@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Git4Mark** [comment]
That problem was solved，yarn is useful
