### ISSUE TITLE
The C++ code  does't seem to work

### ISSUE THREAD

**Issue by gaojian19930607** [algorithm-visualizer/algorithm-visualizer#256]
when i build the C++ code . it has a error , like this :
![错误](https://user-images.githubusercontent.com/43981435/59341077-c50b1180-8d39-11e9-8e9c-0adc6261268d.PNG)
This is the code:
![代码](https://user-images.githubusercontent.com/43981435/59341094-d3592d80-8d39-11e9-84c3-6c155ad94530.PNG)

Thank for your help .

**Comment by parkjs814** [comment]
I think on **line 18**, it should be `{` and `}` instead of `[` and `]`:
```cpp
VerticalLayout verticalLayout = VerticalLayout({chart, tracer, logger})
```

I'll probably be writing documentation for the C++ library soon, thanks.

**Comment by gaojian19930607** [comment]
OK, thank you very much

**Comment by barbu110** [comment]
Hi! i am getting the same issue with a brand new C++ source file. Everything inside the file seems to be right.
