### ISSUE TITLE
Question: Monolithic Repo?

### ISSUE THREAD

**Issue by chrisVillanueva** [algorithm-visualizer/algorithm-visualizer#289]
This is a great project.  Have you considered grouping the project's multiple repositories under a single repository with yarn workspaces?

**Comment by 64json** [comment]
Hi @chrisVillanueva, even though I am a huge fan of monolithic repo (with Yarn Workspaces and Lerna), I am thinking of just keeping them separate due to CI/CD and GitHub Issues.
