### ISSUE TITLE
Algorithm visualizer does not work with user defined algorithm

### ISSUE THREAD

**Issue by DeepakAtariya** [algorithm-visualizer/algorithm-visualizer#293]
Algorithm visualizer does not work with user-defined algorithm.
I tried to build an array sum code but I did not see the visualisation of the given array and the trace of summation.

**Comment by 64json** [comment]
Hey, I would need to know what your code and the error message are.

**Comment by DeepakAtariya** [comment]
It doesn't show anything. Try writing a sum of an array program and see whether it showing any blocks or not.

**Comment by 64json** [comment]
I can't do much without looking at your code. Reopen it once you have your code posted.
