### ISSUE TITLE
how to work offline

### ISSUE THREAD

**Issue by dreverlyu** [algorithm-visualizer/algorithm-visualizer#294]
Hi guys，how does the project work offline? thanks for your anwser.

**Comment by 64json** [comment]
Hi @dreverlyu, sorry to let you know that it doesn't work offline at this moment.

**Comment by dreverlyu** [comment]
> Hi @dreverlyu, sorry to let you know that it doesn't work offline at this moment.

Oh, It's a pity. thank you~
