### ISSUE TITLE
Github authentication is broken

### ISSUE THREAD

**Issue by eamonwoortman** [algorithm-visualizer/algorithm-visualizer#303]
Hi! 

First of, awesome product, I love how this allows us to visualize algorithms and data structures, so thank you!

I tried to login and create a gist of my own but the authentication (after successfully linking GitHub) lands on an empty white page.
The console logs the following error;
```log
Uncaught TypeError: Cannot read property 'signIn' of null
```
The code it self tries to access the `window.opener` field but that is null. 

After some googling, it seems to be an issue with `window.opener` becoming null after a cross-domain-redirect. I'm not that familiar with the HTTP protocol, but it sounds like there's something with the same-origin security protocols. 

Also, it's worth saying Github is changing it's authentication protocol (removing query auth); https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/

Browser;

- `Brave - Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)`, 
- `Chrome - Version 89.0.4389.114 (Official Build) (64-bit)` 
- `FireFox - 87.0 (64-bit)`

**Comment by 64json** [comment]
Hi @eamonwoortman, sorry for taking almost a year -- didn't have much capacity to maintain it. It should now be fixed, thanks!
