### ISSUE TITLE
The SSL Certficate for algorithm Visualizer website is out of date

### ISSUE THREAD

**Issue by duya123** [algorithm-visualizer/algorithm-visualizer#326]
Your SSL certificate had been out of date on Mar.20, maybe you should update it. :)

**Comment by bookerdong** [comment]
你的邮件已收到

**Comment by lxzzz** [comment]
[自动回复]您的邮件已收到，会尽快给您答复。

**Comment by 64json** [comment]
Thanks for letting me know. It is now fixed.

**Comment by yfunk** [comment]
@64json The SSL certificate expired again a few days ago.

**Comment by 64json** [comment]
@yfunk thanks for letting me know, fixed
