### ISSUE TITLE
Which node version?

### ISSUE THREAD

**Issue by Wizard-F** [algorithm-visualizer/algorithm-visualizer#327]
What's the node version for Algorithm Visualizer projects? I'm using node v16 and have bugs with `npm install`. I can't find the node version anywhere. 

BTW, do you have documents that describe project architecture or *internal* API's (like visualization commands used by the `applyCommand` function in [this file](https://github.com/algorithm-visualizer/algorithm-visualizer/blob/master/src/components/VisualizationViewer/index.js))? If so, is it possible to view them?

**Comment by Wizard-F** [comment]
Node v10 doesn't work either. 

Please help 😢 @64json @jeffslofish @MarkKoz @nadr0

**Comment by 64json** [comment]
The server is running on `v10.15.3`.
