### ISSUE TITLE
What will happen when the user changes the position of the cursor?

### ISSUE THREAD

**Issue by Wizard-F** [algorithm-visualizer/algorithm-visualizer#328]
According to the code snippet below, when the user changes the position of the cursor:

- if the cursor is moved forward (line 37), the visualizer will only apply the chunks between `oldCursor` and `cursor`
- if the cursor is moved to a former position (line 39), the visualizer will simply reset and then re-apply all the chunks from the start to `cursor`

https://github.com/algorithm-visualizer/algorithm-visualizer/blob/1ba46445eba0524bd26f202836bb704842af5f39/src/components/VisualizationViewer/index.js#L35-L51

Is my understanding correct?

**Comment by 64json** [comment]
Yes, it is correct :)
