### ISSUE TITLE
Why not combine tracer initialization and tracer.set()?

### ISSUE THREAD

**Issue by Wizard-F** [algorithm-visualizer/algorithm-visualizer#332]
In the screenshot below, it seems plausible to combine line 19 (tracer initialization) and line 24 (tracer.set()) into one concise line, e.g., `const tracer = new GraphTracer(G).directed(true).weighted();`. 

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/95689995/162929282-01648999-2592-4a83-baa0-af9d1bd6ef3d.png">

Is there any side effect with this approach?

**Comment by 64json** [comment]
The first argument of the `GraphTracer` constructor is the title. https://algorithm-visualizer.github.io/tracers.js/classes/graphtracer.html#constructor

**Comment by Wizard-F** [comment]
I mean, when you design the API, what makes you decide to use two lines (tracer initialization and tracer.set()), as in 

```
const tracer = new GraphTracer().directed(true).weighted();
tracer.set(G);
```

instead of one line like

```
const tracer = new GraphTracer('Graph', G).directed(true).weighted();
```

?

**Comment by 64json** [comment]
Don't remember much because it was 6 years ago, but I guess I wanted to separate tracer initialization from data management.

**Comment by Wizard-F** [comment]
Separation of tracer initialization and data management allows, say, an array tracer to change the array it traces, which may be useful in certain cases. But in my opinion, it would be nice to provide a shortcut like

```
const tracer = new GraphTracer('Graph', G)
```

at the same time :-)
