### ISSUE TITLE
Share limit because of GitHub Gist API

### ISSUE THREAD

**Issue by parkjs814** [algorithm-visualizer/algorithm-visualizer#68]
It seems GitHub Gist API limits the number of creating Gists from unauthenticated request.

```
{
    "message": "API rate limit exceeded for 173.185.182.82. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by TornjV** [comment]
The limit seems to be 60 requests per hour, and is tied to local user.
It is not the best solution, but is good enough for now since it's unlikely that many will normally share more than they're allowed.

**Comment by parkjs814** [comment]
Yea that's true.
Once we support authenticated one, the user can view all the files (s)he shared. That will be awesome.
